---
- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable

- name: Install Nginx
  apt: pkg=nginx state=installed update_cache=true
  when: ppastable|success
  register: nginxinstalled
  notify:
  - Start Nginx

- name: Add H5BP Config
  when: nginxinstalled|success
  copy: src=h5bp dest=/etc/nginx owner=root group=root

- name: Remove Default Site
  when: nginxinstalled|success
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Add Site Config
  when: nginxinstalled|success
  register: sfhconfig
  template: "src=mysite.com.j2 dest=/etc/nginx/sites-available/{{ domain }}.conf owner=root group=root"

- name: Enable Site Config
  when: sfhconfig|success
  file: "src=/etc/nginx/sites-available/{{ domain }}.conf dest=/etc/nginx/sites-enabled/{{ domain }}.conf state=link"

- name: Create Web root
  when: nginxinstalled|success
  file: "dest=/var/www/{{ domain }}/public mode=775 state=directory owner=www-data group=www-data"
  register: webrootinstalled
  notify:
  - Reload Nginx

- name: Install Content
  when: webrootinstalled|success
  template: "src=index.j2 dest=/var/www/{{ domain }}/public/index.html mode=755 owner=www-data group=www-data"

- name: Web Root Permissions
  when: nginxinstalled|success
  file: "dest=/var/www/{{ domain }} mode=775 state=directory owner=www-data group=www-data recurse=yes"
  notify:
  - Reload Nginx
